### ISSUE TITLE
mongodb的in查询问题

### ISSUE THREAD

**Issue by chevanhope** [AaronJan/Academe#2]
在mongodb里，当字段a类型为数组，在进行in查询的时候必须嵌套二维数组查询，一维数组查询则没有结果。

a实际值为：
`a:[1,2,3,4,5]`

当用
`->in('a', [1,2])`查询时，不会有任何结果。

必须用
`->in('a', [[1,2]])`查询，才会有正常结果。

**Comment by AaronJan** [comment]
已解决（包括 `equal` 条件）https://github.com/AaronJan/Academe/releases/tag/v0.22.0
